slug: services
sections: ['pricing_table']

title:    'Services'
short_title: "Services"
heading:  'Discover CommTrack Support & Services.'
desc:     "Our field managers & analysts are here to help."

compare_button: "Compare Plans"
compare_heading: "Compare CommTrack Plans"

css_id: services

locale:
  fr:
    slug: services
    sections: ['pricing_table']

    title:    'Les services'
    short_title: "Les services"
    heading:  "Découvrez l'aide et les services de CommTrack."
    desc:     "Nos coordonnateurs de terrain et analystes sont là pour vous aider."

    compare_button: "Comparez les forfaits de services"
    compare_heading: "Comparez les forfaits de services CommTrack"
